global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
#   - "alert.rules.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - "alertmanager:9093"

scrape_configs:
  - job_name: "search-service"
    static_configs:
      - targets: ["search-service:4002"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # - job_name: "node"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]

  - job_name: "elastic"
    static_configs:
      - targets: ["elastic-exporter:9114"]