services:
  user-service-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - connectsphere
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usersdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service-cache:
    image: redis:8.2.2-alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - connectsphere
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  user-service:
    build: .
    depends_on:
      user-service-db:
        condition: service_healthy
      user-service-cache:
        condition: service_healthy
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=dev
    networks:
      - connectsphere

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@user-service-db:5432/usersdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      user-service-db:
        condition: service_healthy
    networks:
      - connectsphere

  redis-exporter:
    image: bitnami/redis-exporter:latest
    command:
      - "--redis.addr=redis://user-service-cache:6379"
    ports:
      - "9121:9121"
    depends_on:
      user-service-cache:
        condition: service_healthy
    networks:
      - connectsphere

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - connectsphere

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - connectsphere

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    depends_on:
      user-service-db:
        condition: service_healthy
      user-service-cache:
        condition: service_healthy
      postgres-exporter:
        condition: service_started
      redis-exporter:
        condition: service_started
      node-exporter:
        condition: service_started
      alertmanager:
        condition: service_started
    networks:
      - connectsphere

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      # - ./monitoring/grafana/dashboards-data:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - connectsphere

networks:
  connectsphere:
    driver: bridge

volumes:
  pgdata:
